---
- name: Configure network devices based on operating system
  hosts: all
  gather_facts: false
  strategy: free
  tasks:
    - name: configure {{ inventory_hostname }}
      junipernetworks.junos.junos_config:
        src: "{{ inventory_hostname }}.j2"
